config/routes.rb
Rails.application.routes.draw do
  root 'flashcards#index'
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout
  get 'signup' => 'users#new', :as => :signup

  resources :cards, except: :show
  resources :users
  resources :user_sessions

  resources :decks do
    member do
      put 'set_current'
    end
  end

  resources :cards do
    member do
      post 'check_original_text_card'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  attr_reader :picture_remote_url
  belongs_to :user
  belongs_to :deck

  validates :original_text, :translated_text, :review_date, :deck_id, presence: true
  validate :check_text

  before_validation :set_review_date, unless: :review_date?

  has_attached_file :picture, styles: { original: '360x360>' }
  validates_attachment_content_type :picture,
                                    content_type: %r{\Aimage\/.*\z}

  scope :on_review_date, -> { order(review_date: :desc) }
  scope :sort_random, -> { order(Arel.sql('RANDOM()')) }
  scope :dated, -> { where('review_date <= ?', Time.now) }

  def self.send_notifications_mailer
    User.joins(:cards).merge(Card.dated).uniq.each do |user|
      NotificationsMailer.pending_cards(user).deliver_now
    end
  end

  def just_text(translated_text)
    DamerauLevenshtein.distance(original_text.downcase, translated_text.downcase)
  end

  def set_review_date
    self.review_date = new_review_date
  end

  def new_review_date
    Time.now + repetition_period
  end

  def repetition_period
    days_interval = { 0 => 0, 1 => 12.hours, 2 => 3.days, 3 => 1.week, 4 => 2.week }
    days_interval.fetch(try_count, 1.month)
  end

  def rise_try_count
    update(try_count: try_count + 1, mistake_count: 0, review_date: new_review_date)
  end

  def process_mistake
    update(mistake_count: mistake_count + 1)
    update(try_count: 0, mistake_count: 0) if mistake_count == 3
  end

  def check_text
    return errors.add(:translated_text, 'Должна быть разница между оригинальным и переведенным текстом') if original_text.casecmp?(translated_text)
  end

  def picture_remote_url=(url_value)
    if url_value.present?
      self.picture = URI.parse(url_value)
      @picture_remote_url = url_value
    end
  end
end

app/models/deck.rb
class Deck < ApplicationRecord
  belongs_to :user
  has_many :cards, dependent: :destroy

  validates :title, presence: true, uniqueness: { case_sensitive: false, scope: :user_id }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :cards
  has_many :decks, dependent: :destroy
  belongs_to :current_deck, class_name: 'Deck', optional: true

  validates :password, length: { minimum: 5 }, if: lambda {
    new_record? || changes[:crypted_password]
  }

  validates :password, confirmation: true, if: lambda {
    new_record? || changes[:crypted_password]
  }
  validates :password_confirmation, presence: true, if: lambda {
    new_record? || changes[:crypted_password]
  }

  validates :email, uniqueness: true, presence: true

  authenticates_with_sorcery!

  def author?(resource)
    resource.user_id == id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  private

  def not_authenticated
    redirect_to login_path, alert: 'Пожалуйста войдите'
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: %i[edit update destroy check_original_text_card]

  def index
    @cards = current_user.cards.on_review_date
  end

  def new
    @card = current_user.cards.build
  end

  def create
    @card = current_user.cards.build(card_params)
    if @card.save
      redirect_to cards_path, notice: 'Карточка создана'
    else
      render :new
    end
  end

  def edit; end

  def update
    if current_user.author?(@card)
      @card.update(card_params)
      redirect_to cards_path, notice: 'Карточка обновлена'
    else
      render :edit
    end
  end

  def destroy
    if current_user.author?(@card)
      @card.destroy
      redirect_to cards_path, notice: 'Карточка удалена'
    else
      redirect_to cards_path, notice: 'Произошла ошибка'
    end
  end

  def check_original_text_card
    check_result = @card.just_text(params[:answer])
    if check_result < 1
      @card.rise_try_count
      flash[:success] = "Верно"
    elsif check_result == 1
      @card.rise_try_count
      flash[:danger] = "Вы ввели ответ #{params[:answer]} но правильный ответ: #{@card.original_text}"
    else
      @card.process_mistake
      flash[:error] = "Не угадал, правильный ответ: #{@card.original_text}"
    end
    @card.save

    redirect_to root_path
  end

  private

  def set_card
    @card = Card.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:original_text, :translated_text, :picture, :deck_id, :review_date)
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: %i[edit update destroy show set_current]

  def index
    @decks = current_user.decks.order(created_at: :desc)
  end

  def show; end

  def new
    @deck = current_user.decks.new
  end

  def create
    @deck = current_user.decks.new(deck_params)
    if @deck.save
      redirect_to decks_path, notice: 'Колода создана'
    else
      render :new, notice: @deck.errors.full_messages.to_sentence
    end
  end

  def edit; end

  def update
    if @deck.update(deck_params)
      redirect_to decks_path, notice: 'Доска обновлена'
    else
      render :edit, notice: @deck.errors.full_messages.to_sentence
    end
  end

  def destroy
    if @deck.destroy
      redirect_to decks_path, notice: 'Колода удалена'
    else
      redirect_to root_path, notice: 'Произошла ошибка'
    end
  end

  def set_current
    @deck.set_current
    redirect_to @deck
  end

  private

  def set_deck
    @deck = current_user.decks.find(params[:id])
  end

  def deck_params
    params.require(:deck).permit(:title)
  end
end

app/controllers/flashcards_controller.rb
class FlashcardsController < ApplicationController
  def index
    @card = if current_user && current_user.current_deck.nil?
      Card.dated.sort_random.last
    elsif current_user.current_deck.present?
      current_user.current_deck.cards.dated.sort_random.last
    else
      nil
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, expect: [:destroy]

  def new
    @user = User.new
  end

  def create
    if (@user = login(user_params[:email], user_params[:password]))
      redirect_back_or_to(:users, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to login_path, notice: 'Logged out!'
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update show destroy]
  skip_before_action :require_login, only: %i[index new create]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to @user, notice: 'Пользователь зарегистрирован'
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if current_user.update(user_params)
      redirect_to @user, notice: 'Пользователь успешно обновлен.'
    else
      render :edit
    end
  end

  def destroy
    if current_user.destroy
      redirect_to users_url, notice: 'Пользователь удален'
    else
      redirect_to root_path, notice: 'Произошла ошибка'
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/_form.html.erb
<%= simple_form_for @card, html: { multipart: true } do |f| %>
  <%= f.association :deck, collection: current_user.decks %>
  <%= f.input :original_text %>
  <%= f.input :translated_text %>
  <p>Выберите изображение</p>
  <%= image_tag @card.picture.url if @card.picture? %>
  <%= f.input :picture, as: :file, id: 'picture' %>
  <p>Или вставьте ссылку на изображение</p>
  <%= f.input :picture_remote_url, id: 'picture_remote_url' %>
  <%= f.submit %>
<% end %>

app/views/cards/edit.html.erb
<h1>Редактирование карточки</h1>
<%= render 'cards/form' %>

app/views/cards/index.html.erb
<div class="container">
<h1><center>Полный список карточек</center></h1>
  <table class = "table">
    <thead>
      <tr>
        <th>Оригинал</th>
        <th>Перевод</th>
        <th>Дата</th>
        <th>Редактировать</th>
        <th>Удалить</th>
      </tr>
    </thead>
    <tbody>
      <% @cards.each do |c| %>
        <tr>
          <td><%= c.original_text %></td>
          <td><%= c.translated_text %></td>
          <td><%= c.review_date&.strftime("%d/%m/%Y") %></td>
          <td><%= link_to 'Редактировать', edit_card_path(c.id) %></td>
          <td><%= link_to 'Удалить', c, method: :delete, data: { confirm: 'Вы уверены?' }, :class => 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/cards/new.html.erb
<h1>Создать карточку</h1>
<%= render 'cards/form' %>

app/views/decks/_form.html.erb
<%= simple_form_for @deck, html: { multipart: true } do |f| %>
  <%= f.input :title, label: 'Название колоды' %>
  <%= f.submit %>
<% end %>

app/views/decks/edit.html.erb
<h1>Редактирование колоды</h1>
<%= render 'decks/form' %>

app/views/decks/index.html.erb
<div class="container">
<h1><center>Полный список колод</center></h1>
<% if @decks.empty? %>
  <h3>Создайте колоду:</h3>
  <%= link_to "Добавить колоду", new_deck_path, class: 'btn btn-secondary' %>
<% else %>
  <table class = "table">
    <thead>
      <tr>
        <th>Название</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @decks.each do |deck| %>
        <tr>
          <td><%= link_to deck.title, deck %></td>
          <td><%= link_to 'Редактировать', edit_deck_path(deck) %></td>
          <td><%= link_to 'Удалить', deck_path(deck), method: :delete, data: { confirm: 'Вы уверены?' }, :class => 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
</div>

app/views/decks/new.html.erb
<h1>Создание колоды</h1>
<%= render 'decks/form' %>

app/views/decks/show.html.erb
<div class="container">
<h1><center>Полный список карточек в колоде:</center></h1>
  <br>
  <table class = "table">
    <thead>
      <tr>
        <th>Название колоды</th>
        <th>Оригинальный текст</th>
        <th>Переведенный текст</th>
        <th>Дата</th>
      </tr>
    </thead>
    <tbody>
    <% if @deck.cards.empty? %>
      <p>В колоде нет карт</p>
    <% else %>
      <% @deck.cards.each do |c| %>
        <tr>
          <td><%= c.deck.title %></td>
          <td><%= c.original_text %></td>
          <td><%= c.translated_text %></td>
          <td><%= c.review_date&.strftime("%d/%m/%Y") %></td>
        </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>
</div>

app/views/flashcards/index.html.erb
<section>
  <p style="font-size: 22px">
    Первый в мире удобный менеджер флеш-карточек. Именно так.
  </p>
</section>
<section>
<% if @card.present? %>
  <% if @card.picture %>
    <%= image_tag @card.picture.url, id: 'picture' %>
  <% end %>
  Переведенный текст: <%= @card.translated_text %>
  <%= form_tag check_original_text_card_card_path(@card.id) do %>
    <%= hidden_field_tag :id, @card.id %>
    <%= label :answer, 'Оригинальный текст' %>
    <%= text_field_tag :answer %>
    <%= submit_tag 'Проверить введеный текст' %>
  <% end %>
<% else %>
  <h2>Сегодня нет карточек для проверки<h2>
<% end %>
</section>

app/views/layouts/_header.html.erb
<header class="clearfix">
<% if current_user %>
  <h1>Флэшкарточкер</h1>
    <ul class="navigation-links">
      <%= link_to "Добавить колоду", new_deck_path, class: 'btn btn-secondary' %>
      <%= link_to "Все колоды", decks_path, class: 'btn btn-primary' %>
      <%= link_to "Добавить карточку", new_card_path, class: 'btn btn-secondary' %>
      <%= link_to "Все карточки", cards_path, class: 'btn btn-primary' %>
    </ul>
<% else %>
  <h3>Пожалуйста войдите в систему</h3>
<% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Флэшкарточкер</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>
    <ul class="nav justify-content-center">
      <% if current_user %>
        <li class="nav-item">
          <%= link_to "Изменить профиль", edit_user_path(current_user.id), class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Выйти", :logout, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Зарегистрироваться", new_user_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Войти", :login, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>

    <section id="container">
      <%= render 'layouts/header'%>
      <%= yield %>
    </section>
    <% flash.each do |key, value| %>
      <flash class=<%="flash-#{key}"%>>
        <%= value %>
      </flash>
    <% end %>
  </body>
</html>

app/views/user_sessions/_form.html.erb
<%= simple_form_for :user, url: user_sessions_path do |f| %>
  <%= f.input :email, label: 'Электронный адрес' %>
  <%= f.input :password, label: 'Пароль' %>
  <%= f.button :submit, 'Вход' %>
<%end%>

app/views/user_sessions/new.html.erb
<h1> Аутентификация </h1>
<%= render 'form' %>

<%= link_to 'Назад', user_sessions_path %>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>
  <%= f.input :email, label: 'Электронный адрес' %>
  <%= f.input :password, label: 'Пароль' %>
  <%= f.input :password_confirmation, label: 'Подтверждение' %>
  <%= f.button :submit, 'Сохранить' %>
<% end %>

app/views/users/edit.html.erb
<h1>Изменить профиль</h1>
<%= render 'form', user: @user %>

<%= link_to 'Детали', @user %>
<%= link_to 'Назад', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Пользователи</h1>
<table>
  <thead>
    <tr>
      <th>email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <% if user === current_user %>
          <td><%= link_to 'Детали', user %></td>
          <td><%= link_to 'Изменить', edit_user_path(user) %></td>
          <td><%= link_to 'Удалить', user, method: :delete, data: { confirm: 'Вы уверены?' }, :class => 'btn btn-danger' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Новый пользователь', new_user_path %>

app/views/users/new.html.erb
<h1>Регистрация</h1>
<%= render 'form', user: @user %>

<%= link_to 'Назад', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Изменить', edit_user_path(@user) %> |
<%= link_to 'Назад', users_path %>